### ISSUE TITLE
ALP1 hardcoded in stream definition_datm.xml

### ISSUE THREAD

**Issue by ecaas** [huitang-earth/scripts_ctsm_region#1]
Hi, 
I'm doing some test simulations with the VCG sites on Saga, and ran into an issue, 
In [the stream definition file](https://github.com/huitang-earth/scripts_ctsm_region/blob/main/atm_forcing/cosmo_rea_6km/ctsm_config_VCG/stream_definition_datm.xml) ALP1 is hardcoded in line [380](https://github.com/huitang-earth/scripts_ctsm_region/blob/main/atm_forcing/cosmo_rea_6km/ctsm_config_VCG/stream_definition_datm.xml#L380), line [412](https://github.com/huitang-earth/scripts_ctsm_region/blob/main/atm_forcing/cosmo_rea_6km/ctsm_config_VCG/stream_definition_datm.xml#L412) and line [447](https://github.com/huitang-earth/scripts_ctsm_region/blob/main/atm_forcing/cosmo_rea_6km/ctsm_config_VCG/stream_definition_datm.xml#L447). This causes all sites to use ALP1 forcing, and not the appropriate site forcing. I attached an atm log file for a BOR2 simulation, showing the issue:
[atm.log.7850963.zip](https://github.com/huitang-earth/scripts_ctsm_region/files/10941933/atm.log.7850963.zip)
(The log file ends in a dtlimit error but I don't think that is related to this ALP1 issue...)

I'm not too familiar with the syntax, but it might be quickly fixed by replacing "ALP1" by "%"? ~~I'll try that and make a pull request to change the file here if it works.~~ That did not work...

@evalieungh FYI!

**Comment by huitang-earth** [comment]
Hi @ecaas , thanks for noticing this. Yes, I have not gone further with other sites using the new version of the model. As you know that I am running moss work with relatively old version. 

If you look the file, there should be some more generic parameters which automatically change with the case/site you run (e.g., $CLM_USRDAT_NAME). You can use such parameters (or create your own like $NEONSITE) to set the site in a more automatic way. I have not texted myself. But I hope it could work.

Or else, you have to manually change the site name. 

If you have be able to solve the issue in a few hours, just let me know. I will provide you a better solution during the weekend. You can then test it.

**Comment by huitang-earth** [comment]
@ecaas Did you change your calendar to Gregorian?

**Comment by ecaas** [comment]
Ok, thank you for pointing me to the generic parameters, I should be able to find a solution from that. Don't spend your weekend on that!

I have not changed my calendar. Might that be related to the dtlimit error then?

**Comment by huitang-earth** [comment]
Yes. I see the error first indicate that the year is somehow 366. :)

I think I forget to mention the calendar issue in the instruction. I will add that.

**Comment by ecaas** [comment]
Great thanks, that seems to fix the problem!:) I also found a way of pointing to the correct stream files, I made a pull request on that.

**Comment by evalieungh** [comment]
Interesting! I'll look at how this will work in the platform. The ALP1 hardcoding might explain some of the issues I've had when I tried to run tests for other sites.

**Comment by huitang-earth** [comment]
@ecaas Thanks for the creative work with the sites names. 
@evalieungh If you find this is the problem also for the platform, perhaps you could adopt the solution from Elin for changing site names automatically.
